#!/bin/sh

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

manual_add_modules 'bcachefs'

# chacha20 and poly1305 are used for encrypted bcachefs filesystems.
add_loaded_modules 'chacha20[-_]*'
add_loaded_modules 'poly1305[-_]*'

# Add the bcachefs utility to the initramfs
# Note: make install replaces this with the install path, so it must be last
#copy_exec /usr/local/sbin/bcachefs /sbin/bcachefs
